### ISSUE TITLE
The last GameLib hotfix introduced a bug when using the GetAccountRealmCharacter function

### ISSUE THREAD

**Issue by olbat** [wildstarnasa/GeminiDB#5]
The last game's hotfix (vers.12403 or the previous one) introduced a bug in the addon.

GeminiDB is now crashing on loading:
```
...dStar\Addons\RaidCore\Libs/GeminiDB/GeminiDB-1.0.lua:285: attempt to call field 'GetAccountRealmCharacter' (a nil value)
stack trace:
...dStar\Addons\RaidCore\Libs/GeminiDB/GeminiDB-1.0.lua:285: in main chunk
```

[This topic on the forum](https://forums.wildstar-online.com/forums/index.php?/topic/149368-the-hotfix-just-broke-a-lot-of-addons/) might be useful: people are trying to find out a solution ...

This bug impacts a lot of popular addons such as:
- [RaidCore](http://www.curse.com/ws-addons/wildstar/227908-raidcore)
- [Interruptor](www.curse.com/ws-addons/wildstar/220057-interruptor)
- [Perspective](www.curse.com/ws-addons/wildstar/222046-perspective)
- [SCastBar](http://www.curse.com/ws-addons/wildstar/220098-scastbar)
- [MailHelper](www.curse.com/ws-addons/wildstar/220565-mailhelper)
- and more ...

Can you please propose a bugfix as quick as possible ?

**Comment by olbat** [comment]
Just made a pull request based on [ZodBain](https://forums.wildstar-online.com/forums/index.php?/user/800050-zodbain/)'s [patch](https://forums.wildstar-online.com/forums/index.php?/topic/149368-the-hotfix-just-broke-a-lot-of-addons/#entry1484815), hope it will help ...

**Comment by NekoNova** [comment]
merged the PR after reviewing it.
The code is a smart temporary fix that will work again the "old fashioned way" when Carbine fixes the API

**Comment by olbat** [comment]
Thank you for your quick answer ! :)
